{
 "title": "Micro Service Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "BTC Messages Produced",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kafka_messages_total{coin=\"BTC\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LTC Messages Produced",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "kafka_messages_total{coin=\"LTC\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API HTTP Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "http_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "XRP Messages Produced",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "kafka_messages_total{coin=\"XRP\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "XMR Messages Produced",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 7 },
   "targets": [
    {
     "expr": "kafka_messages_total{coin=\"XMR\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Request Duration Sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "http_request_duration_seconds_sum",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Coin Price Change Messages Produced",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    { "expr": "kafka_messages_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Price Change Message Processing Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "price_change_message_processing_duration",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}